/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Demas.*;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author Robert
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }
    
    static HashMesa dispersionUsuarios = new HashMesa();
    
    static int tiempo = 0;
    static PriorityQueue impresiones = new PriorityQueue();
    
    //Interfaces
    static Inicio interfazInicial = new Inicio();
    static ColaImpresion verLista = new ColaImpresion();
    static interfazDocumentos interfazDocs = new interfazDocumentos();
    static interfazUsuarios interfazUsers = new interfazUsuarios();
    static interfazImpresion interfazPrint = new interfazImpresion();
    static verListaUsuarios verListaU = new verListaUsuarios();
    static javax.swing.JDialog relojito = new javax.swing.JDialog();
    static vistaArbol arbolito = new vistaArbol();
    
    
    static int segundos = 0;
    static int minutos = 0;    

    static Timer timer = new Timer();
    
    /**
     * cada segundo agrega 1 a tiempo e imprime el tiempo en el reloj
     */
    static TimerTask updateTimer = new TimerTask() {
        public void run(){
            tiempo ++;
            minutos = tiempo / 60;
            segundos = tiempo % 60;
            relojito.setTitle(String.format("%02d", minutos) + ":" + String.format("%02d", segundos));
              
        }
    };
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        irUsuarios = new javax.swing.JButton();
        irDocumentos = new javax.swing.JButton();
        irImpresion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Epson 8008");
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(400, 150));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BIENVENIDO A LA IMPRESORA");

        irUsuarios.setText("Usuarios");
        irUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irUsuariosActionPerformed(evt);
            }
        });

        irDocumentos.setText("Documentos");
        irDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irDocumentosActionPerformed(evt);
            }
        });

        irImpresion.setText("Impresion");
        irImpresion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irImpresionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(irUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(irImpresion, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(irDocumentos)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(irUsuarios)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(irDocumentos)
                        .addComponent(irImpresion)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Abre la pantalla de usuarios
     * @param evt 
     */
    private void irUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irUsuariosActionPerformed
        interfazUsers.setVisible(true);
        this.setVisible(false);
        relojito.setVisible(true);
    }//GEN-LAST:event_irUsuariosActionPerformed

    /**
     * abre pantalla de documentos
     * @param evt 
     */
    private void irDocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irDocumentosActionPerformed
        interfazDocs.setVisible(true);
        this.setVisible(false);
        relojito.setVisible(true);
    }//GEN-LAST:event_irDocumentosActionPerformed

    /**
     * abre pantalla de impresion
     * @param evt 
     */
    private void irImpresionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irImpresionActionPerformed
        interfazPrint.setVisible(true);
        this.setVisible(false);
        relojito.setVisible(true);
    }//GEN-LAST:event_irImpresionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                interfazInicial.setVisible(true);
                interfazInicial.setLocation(320, 400);
                verLista.setVisible(true);
                verLista.setLocation(0, 0);
                verListaU.setVisible(true);
                verListaU.setLocation(300, 0);
                relojito.setVisible(true);
                arbolito.setVisible(true);
                arbolito.setLocation(600, 0);

                interfazDocs.setLocation(900, 0);
                interfazUsers.setLocation(900, 0);
                interfazPrint.setLocation(900, 0);
                relojito.setLocation(0, 400);
                relojito.setAlwaysOnTop(false);
                

                timer.scheduleAtFixedRate(updateTimer, 1000, 1000);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton irDocumentos;
    private javax.swing.JButton irImpresion;
    private javax.swing.JButton irUsuarios;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
